In [28]:
# taking images from camera
import cv2
cap = cv2.VideoCapture(0)

def testVideoCam():
    while True:
        has_frame, frame = cap.read()
        if not has_frame:
            print('No frames are captured')
            break
        #frame = cv2.resize(frame,(160,160))
        cv2.imshow('testFrame',frame)
        key = cv2.waitKey(3)
        if key == 27:
            print('Pressed Esc')
            break
    cap.release()
    cv2.destroyAllWindows()
    return

#testVideoCam()

#capture image for training
for i in range(10):
    has_frame, frame = cap.read()
    if not has_frame:
        print('No frames are captured')
    #frame = cv2.resize(frame,(160,160))
    
cv2.imshow('testFrame',frame)
cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()



In [29]:
#saving the trainImage
filepath = "C:\\FaceRecognitionFiles\\"
cv2.imwrite(filepath+'trainImage.jpg',frame)

True

In [30]:
#detect face from saved trainImage
from PIL import Image
from mtcnn.mtcnn import MTCNN
import numpy as np
import matplotlib.pyplot as plt
import cv2
detector = MTCNN()


In [31]:
# Loading the image in frame variable using opencv
frame = cv2.imread("C:\\FaceRecognitionFiles\\trainImage.jpg")

# Loading haar cascade classifier in classifier variable using opencv
classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Pre-processing the image, converting it to greyscale
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

# Detecting faces from image using classifier (scalefactor[how much image is reduced at each scale], minimum no of neighbours[number of neighbours each candidate should have to retain it])
faces = classifier.detectMultiScale(gray, 1.1, 6)
#faces is a 2d array containing only xywh of all the people detected in the image
#frame = cv2.imread("C:\\FaceRecognitionFiles\\trainImage.jpg")
#trainface_metadata = detector.detect_faces(frame) #extracting faces from trainImage

In [32]:
print('number of faces detected = ', len(faces))

number of faces detected =  1


In [34]:
print(faces[0])

[224 162 233 233]


In [36]:
#detecting face coordinates
#x = int(trainface_metadata[0]['box'][0])
#y = int(trainface_metadata[0]['box'][1])
#w = int(trainface_metadata[0]['box'][2])
#h = int(trainface_metadata[0]['box'][3])
x = faces[0][0]
y = faces[0][1]
w = faces[0][2]
h = faces[0][3]
detected_face = cv2.rectangle(frame, (x,y),(x+w,y+h), color=255, thickness=3) #see the detected face outlines
cv2.imshow('Detected face with rectangle',detected_face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
#cropping the image to required size 160,160
face = frame[y:y+h, x:x+w]
face = Image.fromarray(face)
face = face.resize((160,160))
face = np.asarray(face)

In [38]:
#display cropped image
cv2.imshow('Cropped image', face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
#create face embedding
import tensorflow as tf
from keras_facenet import FaceNet
embedder = FaceNet()

In [42]:
#face embedding generator function
def get_embedding_facenet(face_pixels):
    face_pixels = face_pixels.astype('float32')
    mean, std = face_pixels.mean(), face_pixels.std()
    face_pixels = (face_pixels - mean)/std
    samples = np.expand_dims(face_pixels, axis=0)
    embedding = embedder.model.predict(samples)
    return embedding[0]

In [43]:
trainface_embedding = get_embedding_facenet(face)

1/1 [==============================] - 1s 1s/step


In [44]:
#printing face embedding
print(trainface_embedding)

[ 0.04152646  0.02082708  0.01599292  0.03894857  0.05321268  0.05876885
  0.00184753 -0.00677577 -0.01167484 -0.06622963 -0.05329586 -0.01011575
  0.00689343 -0.00511622  0.02425072 -0.03728476 -0.01084804  0.05191188
  0.03832323  0.02062868 -0.01962681  0.01932536  0.06187895 -0.01828597
  0.06980556  0.03568329  0.10337234 -0.05111944  0.06456415 -0.05201211
 -0.01805717  0.02797248 -0.07328796  0.06159768  0.06526904  0.03633595
  0.04137305  0.00219036 -0.05876808  0.01826699  0.08816267 -0.05229949
 -0.04220127 -0.06203759 -0.08094054 -0.05785367 -0.0295382   0.05436934
 -0.09175251 -0.0127039   0.0009308  -0.04197019  0.00408793  0.07499621
  0.00108911 -0.02617867  0.03994458  0.03353146  0.05709821  0.02073997
  0.03979392 -0.00719269  0.04108038  0.00331393  0.01807653 -0.00948615
  0.05806514 -0.02403394  0.03069177 -0.06462449 -0.01127922 -0.0376946
 -0.00197306  0.01579353  0.04970215 -0.01917705 -0.01071534 -0.01183518
 -0.02006381 -0.04264342  0.06740677 -0.01144532  0.

In [45]:
trainface_embedding.shape

(512,)

In [46]:
#saving trainface embedding in a file
from numpy import savez_compressed
np.savez_compressed("C:\\FaceRecognitionFiles\\puru_face_embedding.npz",trainface_embedding,"Puru")

In [5]:
#testing with other images
import cv2
import tensorflow as tf
from PIL import Image
from mtcnn.mtcnn import MTCNN
import numpy as np
import matplotlib.pyplot as plt
detector = MTCNN()
from keras_facenet import FaceNet
embedder = FaceNet()

In [6]:
#to load an image from filepath

In [46]:
faces = cv2.imread("C:\\FaceRecognitionFiles\\trainImage.jpg")

In [47]:
cv2.imshow('test image', faces)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
#to load image from camera
cap = cv2.VideoCapture(0)

In [53]:
for i in range(10):
    has_image, image = cap.read()
    if not has_image:
        print('No frames are captured')
    #frame = cv2.resize(frame,(160,160))
    
cv2.imshow('testimage',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
frame = image

In [55]:
# Loading the image in frame variable using opencv
#frame = cv2.imread("C:\\FaceRecognitionFiles\\trainImage.jpg")

# Loading haar cascade classifier in classifier variable using opencv
classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Pre-processing the image, converting it to greyscale
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

# Detecting faces from image using classifier (scalefactor[how much image is reduced at each scale], minimum no of neighbours[number of neighbours each candidate should have to retain it])
faces = classifier.detectMultiScale(gray, 1.1, 6)
#faces is a 2d array containing only xywh of all the people detected in the image
#frame = cv2.imread("C:\\FaceRecognitionFiles\\trainImage.jpg")
#trainface_metadata = detector.detect_faces(frame) #extracting faces from trainImage

2/2 [==============================] - 0s 256ms/step


In [56]:
print('number of faces = ',len(faces))

number of faces =  0


In [41]:
print(faces)

[]


In [12]:
x = faces[0][0]
y = faces[0][1]
w = faces[0][2]
h = faces[0][3]
detected_face = cv2.rectangle(faces, (x,y),(x+w,y+h), color=255, thickness=3) #see the detected face outlines
cv2.imshow('Detected face with rectangle',detected_face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#get list of faces
def get_faces(image, faces_metadata, required_size = (160,160)):
    faces = []
    for i in range(len(faces_metadata)):
        face_index=0
        x = int(faces_metadata[i]['box'][0])
        y = int(faces_metadata[i]['box'][1])
        w = int(faces_metadata[i]['box'][2])
        h = int(faces_metadata[i]['box'][3])
        
        face = image[y:y+h, x:x+w]
        face = Image.fromarray(face)
        face = face.resize(required_size)
        face = np.asarray(face)
        faces.append(face)
        
    return faces

In [14]:
facesdata = get_faces(faces, faces_metadata, required_size = (160,160))

In [15]:
print('number of faces = ', len(faces))

number of faces =  3


In [16]:
#get embedding data of all faces
def get_embedding_facenet(face_pixels):
    face_pixels = face_pixels.astype('float32')
    mean, std = face_pixels.mean(), face_pixels.std()
    face_pixels = (face_pixels - mean)/std
    #transform face into one smaple 
    samples = np.expand_dims(face_pixels, axis=0)
    #make prediction to get embedding
    embedding = embedder.model.predict(samples)
    return embedding[0]

In [17]:
face_embeddings = []
for i in range(len(facesdata)):
    face_embedding = get_embedding_facenet(facesdata[i])
    face_embeddings.append(face_embedding)

1/1 [==============================] - 0s 34ms/step


In [18]:
#loading my embedding
def load_numpy_faces(faces_dataset_numpy):
    from numpy import load
    data = load(faces_dataset_numpy)
    faces, labels = data['arr_0'], data['arr_1']
    return faces, labels


In [19]:
faces_dataset_numpy = 'C:\\FaceRecognitionFiles\\puru_face_embedding.npz'
puru_face_embedding, puru_name = load_numpy_faces(faces_dataset_numpy)

In [20]:
faces_distances = np.linalg.norm(face_embeddings - puru_face_embedding, axis=1)

In [21]:
faces_distances

array([0.7161484, 1.2717508, 1.1657768], dtype=float32)

In [22]:
print('face with closest distance is: ', np.argmin(faces_distances))

face with closest distance is:  0


In [23]:
print(facesdata[0])

[[[ 46  54  61]
  [ 54  62  69]
  [ 58  66  73]
  ...
  [ 85 100 109]
  [ 79  94 103]
  [ 83  99 111]]

 [[ 46  54  61]
  [ 52  60  67]
  [ 58  66  73]
  ...
  [ 84  99 108]
  [ 78  93 102]
  [ 80  96 108]]

 [[ 44  52  59]
  [ 48  56  63]
  [ 54  62  69]
  ...
  [ 87 102 111]
  [ 81  96 105]
  [ 82  98 110]]

 ...

 [[ 33  39  38]
  [ 35  41  40]
  [ 36  42  41]
  ...
  [185 180 171]
  [185 180 171]
  [189 182 173]]

 [[ 33  39  38]
  [ 33  39  38]
  [ 34  40  39]
  ...
  [183 178 169]
  [182 177 168]
  [189 182 173]]

 [[ 33  39  38]
  [ 32  38  37]
  [ 32  38  37]
  ...
  [184 179 170]
  [183 178 169]
  [189 182 173]]]


In [26]:
if(faces_distances[np.argmin(faces_distances)] < 1):
    cv2.imshow('Answer', facesdata[np.argmin(faces_distances)])
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print('Face not found')